// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdkmougcjfcfslxozbei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNka21vdWdjamZjZnNseG96YmVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NDc2NTYsImV4cCI6MjA2MTQyMzY1Nn0.l5-FGX1zFI0Qo7ucidJjVoWJQ7Ccw_XV4yo_E9Zk9sg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);